services:
  # config/setup.sh
  setup:
    image: alpine:latest
    container_name: ${PROJECT_NAME}_setup
    volumes:
      - ./config:/config
      - ./applications:/applications
      - ./uploads:/uploads
      - .:/workdir
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
    working_dir: /workdir
    command: sh -c "apk add --no-cache curl unzip bash docker-cli && bash ./config/setup.sh && touch /tmp/setup_complete && tail -f /dev/null"
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/setup_complete"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      - host

  # Caddy Static Site Server - Single site from uploads/sites/dist
  caddy_dist:
    image: caddy:alpine
    container_name: ${PROJECT_NAME}_caddy_dist
    restart: unless-stopped
    ports:
      - "${DIST_PORT:-12012}:80"
      - "${DIST_PORT_SSL:-12013}:443"
    volumes:
      - ./uploads/sites/dist:/srv
      - ./config/dist/Caddyfile:/etc/caddy/Caddyfile
      - ./logs:/var/log/caddy
    depends_on:
      setup:
        condition: service_healthy
    networks:
      - host
      
networks:
  host:
    driver: bridge